-- local MP = ...
-- return {
--   {
--     "cmp-cmdline",
--     auto_enable = true,
--     on_plugin = { "blink.cmp" },
--   },
--   {
--     "blink.compat",
--     auto_enable = true,
--     dep_of = { "cmp-cmdline", "cmp-conjure" },
--   },
--   {
--     "luasnip",
--     auto_enable = true,
--     dep_of = { "blink.cmp" },
--     after = function (_)
--       require(MP:relpath("snippets", 1))
--     end,
--   },
--   {
--     "colorful-menu.nvim",
--     auto_enable = true,
--     on_plugin = { "blink.cmp" },
--   },
--   {
--     "blink.cmp",
--     auto_enable = true,
--     event = "DeferredUIEnter",
--     after = function (plugin)
--       require("blink.cmp").setup({
--         keymap = {
--           preset = "default",
--           ["<Tab>"] = { "select_next", "fallback" },
-- 					["<S-tab>"] = { "select_prev", "fallback" },
-- 					["<C-s>"] = { "show", "show_documentation", "hide_documentation" },
-- 					["<C-k>"] = { "show_signature", "hide_signature", "fallback" },
-- 					["<A-space>"] = {
-- 						function(cmp)
-- 							cmp.show({})
-- 						end,
-- 					},
--         },
--         cmdline = {
--           enabled = true,
--           completion = {
--             menu = {
--               auto_show = true,
--             },
--           },
--           sources = function()
--             local type = vim.fn.getcmdtype()
--             if type == '/' or type == '?' then return { 'buffer' } end
--             if type == ':' or type == '@' then return { 'cmdline', 'cmp_cmdline' } end
--             return {}
--           end,
--         },
--         term = {
--           enabled = false,
--         },
--         fuzzy = {
--           sorts = {
--             'exact',
--             -- defaults
--             'score',
--             'sort_text',
--           },
--         },
--         appearance = {
--           nerd_font_variant = 'mono'
--         },
--         signature = {
--           enabled = true,
--           window = {
--             show_documentation = true,
--           },
--         },
--         completion = {
--           menu = {
--             draw = {
--               columns = {
--                 { "label", "label_description", gap = 1 }, { "srckind" }
--               },
--               treesitter = { 'lsp' },
--             },
--           },
--           documentation = {
--             auto_show = true,
--           },
--         },
--         ---@type blink.cmp.SnippetsConfig
--         snippets = {
--           preset = "luasnip",
--           active = function(filter)
--             local snippet = require "luasnip"
--             local blink = require "blink.cmp"
--             if snippet.in_snippet() and not blink.is_visible() then
--               return true
--             else
--               if not snippet.in_snippet() and vim.fn.mode() == "n" then
--                 snippet.unlink_current()
--                 vim.snippet.stop()
--               end
--               return false
--             end
--           end,
--         },
--       })
--     end,
--   },
-- }
